<?php
/**
 * Copyright 2018 Kustom AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Deutsch";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset' => 'UTF-8',

    'FCKUSTOM_KUSTOMMAINMENU'      => 'Kustom',
    'FCKUSTOM_START'               => 'Start',
    'FCKUSTOM_GENERAL_SETTINGS'    => 'Allgemein',
    'FCKUSTOM_CONFIGURATION'       => 'Konfiguration',
    'FCKUSTOM_CONFIGURATION_KCO'   => 'Konfiguration für Kustom Checkout',
    'FCKUSTOM_KUSTOMDESIGN'        => 'Design Settings',
    'FCKUSTOM_EXTERNAL_PAYMENTS'   => 'External Payment Methods',
    'FCKUSTOM_EXTRA_MERCHANT_DATA' => 'Extra Merchant Data',
    'FCKUSTOM_BASIC_SETTINGS'      => 'basic settings',
    'FCKUSTOM_DISCOUNT_TITLE'      => 'Rabatt',
    'FCKUSTOM_MERCHANT_SUPPORT'    => 'Händler Support',

    'fckustom_tbclkustom_orders' => 'Kustom',
    'FCKUSTOM_NO_OPTIONS_MODE'   => 'In diesem Modus gibt es keine Einstellungen.',
    'FCKUSTOM_CHANGES_SAVED'     => 'Alle Einstellungen wurden gesichert.',

    'FCKUSTOM_EASY'                         => 'So einfach ist es, Kustom zu aktiveren',
    'FCKUSTOM_PHONE'                        => 'Telefon',
    'FCKUSTOM_EMAIL'                        => 'Email',
    'FCKUSTOM_BUSINESS_HOURS'               => 'Geschäftszeiten',
    'FCKUSTOM_MONDAY'                       => 'Montag',
    'FCKUSTOM_TUESDAY'                      => 'Dienstag',
    'FCKUSTOM_WEDNESDAY'                    => 'Mittwoch',
    'FCKUSTOM_THURSDAY'                     => 'Donnerstag',
    'FCKUSTOM_FRIDAY'                       => 'Freitag',
    'FCKUSTOM_SATURDAY'                     => 'Samstag',
    'FCKUSTOM_SUNDAY'                       => 'Sonntag',
    'FCKUSTOM_YOUR_COUNTRY_SPECIFIC_CREDS'  => 'Ihre länderspezifischen Zugangsdaten',
    'FCKUSTOM_ADD_COUNTRY_SPECIFIC_CREDS'   => 'Länderspezifische Zugangsdaten hinzufügen',
    'FCKUSTOM_COUNTRY'                      => 'Land',
    'FCKUSTOM_MERCHANT_ID'                  => 'Merchant ID/API-Benutzernamen',
    'FCKUSTOM_PASSWORD'                     => 'Passwort/API-Passwort',
    'FCKUSTOM_DEFAULT_SHOP_COUNTRY'         => 'Standard Land des Shops',
    'FCKUSTOM_ENABLE_LOGGING'               => 'Logging aktiv',
    'FCKUSTOM_SEND_ADDITIONAL_PRODUCT_DATA' => 'Erweiterte Produktdaten an Kustom senden?',
    'FCKUSTOM_PRODUCT_URLS'                 => 'Produkt URLs',
    'FCKUSTOM_IMAGE_URLS'                   => 'Bild URLs',
    'FCKUSTOM_ENABLE_ANONYMIZATION'         => 'Anonymisieren',
    'FCKUSTOM_ADD'                          => 'Hinzufügen',


    'FCKUSTOM_CHECKOUT_NAME'      => 'Kustom Checkout',

    'FCKUSTOM_CHECKOUT_DESC'     => 'Die Komplettlösung enthält alle wichtigen Zahlarten (Rechnung, Ratenkauf, Sofortüberweisung, Lastschrift, Mastercard und VISA-Card) und wird durch Kustom gehostet. Ihre Kunden müssen beim Bezahlen lediglich E-Mail-Adresse und Postleitzahl eingeben und können ihre bevorzugte Zahlart wählen. Alles mit nur einer Integration.',
    'FCKUSTOM_PAYMENTS_DESC'     => 'Mit Kustom können Endkunden auf drei Arten bezahlen: Sofortüberweisung, später oder in Raten. Das ermöglicht Endkunden, Ware erst zu probieren und nur das zu bezahlen, was sie behalten möchten, Produkte im Shop zu finanzieren oder sofort zu bezahlen. Rechnung, Ratenkauf, Sofortüberweisung oder Lastschrift können Sie mit einer Integration aktivieren und sind dank der iFrame Lösung von Kustom rechtlich und inhaltlich immer auf dem aktuellen Stand.',
    'FCKUSTOM_EASY_AND_SECURE_SHOPPING' => 'Kustom, ehemals Kustom Checkout, ist eine der führenden Checkout-Lösungen Europas. Schnell zu integrieren, einfach zu bedienen.',
    'FCKUSTOM_WELCOME_TO_CONFIGURATION' => 'Herzlich willkommen im Konfigurationsbereich von Kustom. Klicken Sie auf die Kustom-Unterkategorien, um die Installation dieses Moduls abzuschließen.',

    'FCKUSTOM_CREATE_USER_ACCOUNT'                  => 'Kundenkonto im OXID eShop anlegen',
    'FCKUSTOM_SUBSCRIBE_TO_NEWSLETTER'              => 'Newsletter-Anmeldung',
    'FCKUSTOM_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'    => 'Kundenkonto anlegen UND Newsletter-Anmeldung',
    'FCKUSTOM_NO_CHECKBOX'                          => 'Keine Checkbox anzeigen',


    /* design */
    'FCKUSTOM_DISPLAY_ON_HOME'                      => 'Auf der Shop Startseite anzeigen?',
    'FCKUSTOM_BANNER_SRC'                           => 'Kustom Banner Quelle',
    'FCKUSTOM_FOOTER'                               => 'Fußzeile',
    'FCKUSTOM_DISPLAY_IN_FOOTER'                    => 'Was soll in der Fußzeile angezeigt werden?',
    'FCKUSTOM_FOOTER_PAYMENT_METHODS'               => 'Payment Method Display',
    'FCKUSTOM_FOOTER_KUSTOM_LOGO'                   => 'Kustom Logo',
    'FCKUSTOM_DESIGN'                               => 'Design',
    'FCKUSTOM_LONG_VERSION'                         => 'Lange Version:',
    'FCKUSTOM_SHORT_VERSION'                        => 'Kurze Version:',
    'FCKUSTOM_DETAILS_AND_BASKET'                   => 'Artikel-Detailseite',
    'FCKUSTOM_DISPLAY_PAYMENT_WIDGET'               => 'Kustom Payment Method Widget anzeigen?',
    'FCKUSTOM_KCO_SHIPPINGMETHOD'                   => 'Kustom Checkout Versand',
    'FCKUSTOM_ON_BASKET_PAGE'                       => 'Auf der Warenkorb-Seite',
    'FCKUSTOM_PAYMENT_DESIGN'                       => 'Kustom Payment Design Optionen',
    'FCKUSTOM_CHECKOUT_DESIGN'                      => 'Kustom Checkout Design Optionen',
    'FCKUSTOM_COLOR_SETTINGS'                       => 'Farb-Einstellungen:',
    'FCKUSTOM_BORDER'                               => 'Border:',
    'FCKUSTOM_BORDER_SELECTED'                      => 'Border selected:',
    'FCKUSTOM_BUTTON'                               => 'Button:',
    'FCKUSTOM_BUTTON_TEXT'                          => 'Button Text:',
    'FCKUSTOM_CHECKBOX'                             => 'Checkbox:',
    'FCKUSTOM_CHECKBOX_CHECKMARK'                   => 'Checkbox Haken:',
    'FCKUSTOM_DETAILS'                              => 'Details:',
    'FCKUSTOM_HEADER'                               => 'Kopfzeile:',
    'FCKUSTOM_LINK'                                 => 'Link:',
    'FCKUSTOM_TEXT'                                 => 'Text:',
    'FCKUSTOM_SECONDARY_TEXT'                       => 'Weiterer Text:',
    'FCKUSTOM_RADIUS_SETTINGS'                      => 'Radius Einstellung:',
    'FCKUSTOM_BORDER_RADIUS'                        => 'Border Radius:',


    'FCKUSTOM_ALLOW_SEPARATE_SHIPPING_ADDRESS'      => 'Lieferanschrift darf von Rechnungsanschrift abweichen',
    'FCKUSTOM_PHONE_NUMBER_MANDATORY'               => 'Telefonnummer ist Pflichtfeld',
    'FCKUSTOM_DATE_OF_BIRTH_MANDATORY'              => 'Geburtsdatum ist Pflichtfeld',
    'FCKUSTOM_ENABLE_AUTOFOCUS'                     => 'Autofocus für Kustom Checkout Iframe aktivieren ',
    'FCKUSTOM_ADD_A_CUSTOM_CHECKBOX'                => 'Individuelle Checkbox im Kustom Checkout Iframe hinzufügen',
    'FCKUSTOM_ENABLE_DHL_PACKSTATION'               => 'Lieferung an DHL Packstation aktivieren',
    'FCKUSTOM_ENABLE_PRE_FILLING'                   => 'Pre-filling aktivieren',
    'FCKUSTOM_ENABLE_PREFILL_NOTIFICATION'          => 'Pre-filling Hinweis aktivieren',
    'FCKUSTOM_SALUTATION_MANDATORY'                 => 'Anrede ist Pflichtfeld',
    'FCKUSTOM_SET_TAC_URI'                          => 'URL zu Ihren AGB - Pflichtfeld',
    'FCKUSTOM_SET_CANCEL_URI'                       => 'URL zum Widerrufsrecht - Pflichtfeld',
    'FCKUSTOM_SHIPPING_DETAILS'                     => 'URL zu Versanddetails - Pflichtfeld',
    'FCKUSTOM_NO_VALIDATION_NEEDED'                 => 'Keine Validierung',
    'FCKUSTOM_VALIDATION_IGNORE_TIMEOUTS_NEEDED'    => 'Validierung durchführen, aber Timeouts ignorieren',
    'FCKUSTOM_SUCCESSFUL_VALIDATION_NEEDED'         => 'Erfolgreiche Validierung erforderlich',
    'FCKUSTOM_ORDER_VALIDATION'                     => 'Bestell-Validierung',

    'FCKUSTOM_KUSTOM.'                        => 'Kustom (ehemals Kustom Checkout).',
    'FCKUSTOM_KUSTOM_START'                   => 'Für Kunden, die jetzt kaufen und später bezahlen möchten. Ganz bequem in 30 Tagen, je nach Markt.',
    'FCKUSTOM_TRUSTED.'                       => 'Eine vertrauenswürdige und nahtlose Erfahrung',
    'FCKUSTOM_TRUSTED_START'                  => 'Der Bezahlvorgang sollte mühelos ablaufen. Dank mobilem Erlebnis, vorab ausgefüllter Adresse und Express-Checkout erledigen Ihre Kunden den Einkauf im Handumdrehen. So reduzieren Sie Abbrüche und gewinnen Kunden zurück.',
    'FCKUSTOM_WAY.'                           => 'Lassen Sie Ihre Kunden selbst entscheiden wie sie bezahlen',
    'FCKUSTOM_WAY_START'                      => 'Geben Sie Ihren Kunden die Flexibilität, sofort oder später mit der von ihnen bevorzugten Zahlungsmethode zu bezahlen. Egal, wo Sie verkaufen, Kustom unterstützt alle gängigen Optionen wie Karten, Kustom, Banküberweisung, Swish, Apple Pay, MobilePay und mehr, sodass Sie in jedem Markt die Konversionsrate steigern.',
    'FCKUSTOM_QUICK'                          => 'Schnell zu integrieren, einfach zu betreiben',
    'FCKUSTOM_QUICK_START'                    => 'Einfaches Starten und Skalieren mit einer Integration für Zahlungen, Versand, Märkte und Währungen.',
    'FCKUSTOM_CHECKOUT'                       => 'Der Kustom Checkout.',
    'FCKUSTOM_CHECKOUT_START'                 => 'Das beste Checkout-Erlebnis für Ihre Kunden. Zuverlässige Kundenidentifizierung und Versandauswahl. Alle Zahlungen inklusive Weltweite Verfügbarkeit, lokal optimiert. Wir übernehmen das ganze Risiko und Sie erhalten immer Ihr Geld.',

    'FCKUSTOM_RB_HOW_TO_ACTIVATE'             => 'How-to-activate<br>Kustom guide.',
    'FCKUSTOM_RB_HOW_TO_ACTIVATE_LIST_ONE'    => 'Klicken Sie im OXID-Backend auf den neuen Menüpunkt Kustom, die Unterkategorie „Allgemeine Einstellungen“, und geben Sie Ihre Zugangsdaten (Benutzername und Passwort) ein und nehmen Sie unter Shop-Einstellungen > Zahlungsarten und > Versandarten die OXID-typischen Zuordnungen für Zahlungsarten vor.',
    'FCKUSTOM_RB_HOW_TO_ACTIVATE_LIST_TWO'    => 'Speichern Sie die Änderungen.',
    'FCKUSTOM_RB_HOW_TO_ACTIVATE_LIST_THREE'  => 'Sie sind jetzt online und können mit dem Verkaufen mit Kustom beginnen.',
    'FCKUSTOM_RB_MERCHANT_SUPPORT'            => 'Merchant Support',
    'FCKUSTOM_DEVICE_IMG'                     => 'device.png',


    'FCKUSTOM_EXTERNAL_PAYMENTS_ADMIN_DESC'   =>
        'Hier können Sie externe Bezahlarten und externe Checkouts zur Einbindung innerhalb des Kustom Checkout Iframes konfigurieren. 
        Für eine detaillierte Beschreibung der verschiedenen Einstellungen beachten Sie bitte die Tooltips 
        <i class="fa fa-question-circle-o" aria-hidden="true"></i>, lesen Sie das <a class="cl-ku" href="https://wiki.fatchip.de/public/faqkustom7" target="_blank">Handbuch</a> 
        oder wenden Sie sich an den Kustom Support',
    'FCKUSTOM_EXTRA_MERCHANT_DATA_ADMIN_DESC' => 'Hier können Sie konfigurieren, ob ggf. Extra Merchant Data an Kustom übertragen werden soll. 
Für eine detaillierte Beschreibung der verschiedenen Einstellungen beachten Sie bitte die Tooltips 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lesen Sie das <a class="cl-ku" href="https://wiki.fatchip.de/public/faqkustom7" target="_blank">Handbuch</a> 
oder wenden Sie sich an den Kustom Support',
    'FCKUSTOM_DESIGN_SETTINGS_ADMIN_DESC'     => 'Hier können Sie die Design Einstellungen zur Verwendung mit dem Kustom Modul für den OXID eShop konfigurieren. 
Für eine detaillierte Beschreibung der verschiedenen Einstellungen beachten Sie bitte die Tooltips 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lesen Sie das <a class="cl-ku" href="https://wiki.fatchip.de/public/faqkustom7" target="_blank">Handbuch</a> 
oder wenden Sie sich an den Kustom Support',
    'FCKUSTOM_GENERAL_SETTINGS_ADMIN_DESC'    => 'Für eine detaillierte Beschreibung der verschiedenen Einstellungen beachten Sie bitte die Tooltips 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lesen Sie das <a class="cl-ku" href="https://wiki.fatchip.de/public/faqkustom7" target="_blank">Handbuch</a> 
oder wenden Sie sich an den Kustom Support.',
    'FCKUSTOM_CONFIGURATION_KCO_ADMIN_DESC'   => 'Auf dieser Seite können Sie die Kustom Checkout spezifischen Einstellungen konfigurieren. 
Für eine detaillierte Beschreibung der verschiedenen Einstellungen beachten Sie bitte die Tooltips 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lesen Sie das <a class="cl-ku" href="https://wiki.fatchip.de/public/faqkustom7" target="_blank">Handbuch</a> 
oder wenden Sie sich an den Kustom Support',

    'FCKUSTOM_PAYMENT_METHOD'                 => 'Zahlungsart',
    'FCKUSTOM_EXTERNAL_PAYMENT_METHOD'        => 'External Payment Method',
    'FCKUSTOM_EXTERNAL_CHECKOUT'              => 'External Checkout',
    'FCKUSTOM_IMAGE_URI_EXT_PAYMENT'          => 'Bild URI für External Payment Method',
    'FCKUSTOM_IMAGE_URI_EXT_CHECKOUT'         => 'Bild URI für External Checkout',
    'FCKUSTOM_IMAGE_TIP_69x24'                => 'Bildgröße: 69x24 Pixel',
    'FCKUSTOM_IMAGE_TIP_276x48'               => 'Bildgröße: 276x48 Pixel',
    'FCKUSTOM_USER_GUIDE_DESCRIPTION'         => 'Das Benutzerhandbuch für das Kustom Modul für den OXID eShop können Sie hier einsehen.',
    'FCKUSTOM_USER_GUIDE_LINK'         => 'https://wiki.fatchip.de/public/faqkustom7',
    'FCKUSTOM_USER_GUIDE_BUTTON'         => 'Benutzerhandbuch',

    'FCKUSTOM_CHOOSE' => 'Wählen',

    'FCKUSTOM_CUSTOMER_ACCOUNT_INFO' => 'Customer account info',
    'FCKUSTOM_PAYMENT_HISTORY_FULL'  => 'Payment history full',
    'FCKUSTOM_PASSTHROUGH_FIELD'     => 'Pass-through field',

    'FCKUSTOM_ASSIGN_PAYMENT_METHOD_TYPE'           => 'Typ der Zahlungsart zuordnen:',
    'FCKUSTOM_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY' => 'Welche Bestellungen sollen in der Payment history full berücksichtigt werden?',
    'FCKUSTOM_EMD_ORDER_HISTORY_ALL'                => 'Alle Bestellungen als bezahlt betrachten unabhängig vom oxpaid Datum',
    'FCKUSTOM_EMD_ORDER_HISTORY_PAID'               => 'Nur Bestellungen, mit gesetztem oxpaid Datum übermitteln; unbezahlte Bestellungen ignorieren',
    'FCKUSTOM_EMD_ORDER_HISTORY_NONE'               => 'Alle Bestellungen, die mit dieser Zahlungsart durchgeführt wurden, ignorieren',
    'FCKUSTOM_OTHER_PAYMENT'                        => 'Other payment option',
    'FCKUSTOM_DIRECT_BANKING'                       => 'Direct banking',
    'FCKUSTOM_CARD'                                 => 'Card',

    'FCKUSTOM_TEST_MODE_TOOLTIP'                       => 'Wählen Sie zwischen Playground (Test-Betrieb) und Live (Produktiv-Betrieb). Schalten Sie den Produktiv-Betrieb nur nach erfolgreicher Durchführung von Integrations-Tests und nach Rücksprache mit Ihrem Kustom Integration Manager aktiv.',
    'FCKUSTOM_GLOBAL_MERCHANT_ID_TOOLTIP'              => 'Hinterlegen Sie hier bitte Ihre Kustom Merchant ID. Diese haben Sie in der Willkommens E-Mail von Kustom erhalten. Diese Merchant ID samt Passwort gilt global für alle Länder. Nur falls Sie verschiedene Merchant IDs für unterschiedliche Länder erhalten haben, können Sie weiter unten länderspezifische Zugangsdaten je Land hinzufügen.',
    'FCKUSTOM_GLOBAL_PASSWORD_TOOLTIP'                 => 'Geben Sie hier Ihr Passwort passend zur verwendeten Merchant ID ein. Dieses Passwort haben Sie in der Willkommens E-Mail von Kustom erhalten.',
    'FCKUSTOM_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'    => 'Wählen Sie aus der Auswahl links das Land aus, für das Sie länderspezifische Zugangsdaten von Kustom erhalten haben.',
    'FCKUSTOM_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP' => 'Bitte geben Sie hier die zugehörige Merchant ID für dieses Land ein.',
    'FCKUSTOM_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'    => 'Bitte geben Sie hier das zugehörige Passwort für dieses Land ein.',
    'FCKUSTOM_DEFAULT_COUNTRY_TOOLTIP'          => 'Bitte wählen Sie aus der Liste aus, für welches Land der Kustom Checkout standardmäßig geladen werden sollen, solange der Kunde sein Land noch nicht angegeben hat.',
    'FCKUSTOM_ENABLE_LOGGING_TOOLTIP'                  => 'Aktiviert die Protokollfunktion, damit sämtliche API-Kommunikation mit Kustom in der mysql-Tabelle fckustom_logs aufgezeichnet wird. Dies kann bei der Analyse oder Fehlersuche nützlich sein. Im Produktiv-Betrieb sollte die Funktion abgeschaltet sein, da sich sonst ggf. große Log-Mengen anhäufen und sensitive Daten gespeichert werden.',
    'FCKUSTOM_SEND_PRODUCT_URLS_TOOLTIP'               => 'Senden Sie die URLs der Artikel-Detailseiten der Produkte, die sich im Warenkorb Ihrer Kunden befinden an Kustom, damit Kustom später aus dem Kustom Portal auf Ihre Artikel verlinken kann.',
    'FCKUSTOM_SEND_PRODUCT_IMAGES_TOOLTIP'             => 'Senden Sie die URLs der Artikel-Bilder der Produkte, die sich im Warenkorb Ihrer Kunden befinden an Kustom, damit Kustom diese im Kustom Portal anzeigen kann.',
    'FCKUSTOM_ENABLE_ANONYMIZATION_TOOLTIP'            => 'Aktivieren Sie die Anonymisierung, um die Artikelbezeichnungen der Produkte, die sich im Warenkorb Ihrer Kunden befinden, vor Kustom zu verbergen. Dies wird z.B. für Online-Apotheken empfohlen, sollte aber nur nach Rücksprache mit dem Kustom Integration Manager geschehen.',
    'FCKUSTOM_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP' => 'Falls die Lieferung an eine abweichende Lieferanschrift ermöglicht werden soll, aktivieren Sie diesen Schalter.',
    'FCKUSTOM_MANDATORY_PHONE_TOOLTIP'                 => 'Falls Sie die Angabe einer Telefonnummer zwingend erfordern wollen, aktivieren Sie diesen Schalter. Normalerweise ist für Kustom die Telefonnummer kein Pflichtfeld.',
    'FCKUSTOM_MANDATORY_BIRTH_DATE_TOOLTIP'            => 'Falls Sie die Angabe eines Geburtsdatums zwingend erfordern wollen, aktivieren Sie diesen Schalter. Normalerweise ist für Kustom das Geburtsdatum kein Pflichtfeld. Allerdings ist die Angabe notwendig, um den Kauf auf Rechnung oder eine Ratenzahlung zu ermöglichen.',
    'FCKUSTOM_ENABLE_AUTOFOCUS_TOOLTIP'                => 'Mit Hilfe dieses Schalters aktivieren Sie, dass beim Laden der Seite mit dem Kustom Checkout das Kustom Iframe automatisch fokussiert wird.',
    'FCKUSTOM_CHECKBOX_TOOLTIP'                        => 'Es besteht die Möglichkeit, dass Sie innerhalb des Kustom Checkout Iframes eine zusätzliche Checkbox aktivieren, um dem Kunden anzubieten, ein Kundenkonto zu eröffnen oder sich für Ihren Newsletter anzumelden, oder beides. Sollte bei angeschalter Checkbox der Kunde schon ein Kundenkonto haben bzw. schon für den Newsletter angemeldet sein wird der Text der Checkbox automatisch angepasst oder die Checkbox ggf. komplett ausgeblendet.',
    'FCKUSTOM_VALIDATION_TOOLTIP'                      => 'Hiermit können Sie eine zusätzliche Überprüfung des Warenkorbs aktivieren, die beim Absenden der Kustom Checkout Bestellung noch einmal die Verfügbarkeit der gewünschten Artikel überprüft, um Fehler durch Überverkäufe zu vermeiden. Es wird der Modus \'Erfolgreiche Validierung erforderlich\' empfohlen.',
    'FCKUSTOM_SALUTATION_MANDATORY_TOOLTIP'            => 'Diese Einstellung betrifft ausschließlich das Kustom Checkout Formular für UK: Soll die Angabe der Anrede erzwungen werden?',
    'FCKUSTOM_ENABLE_DHL_PACKSTATIONS_TOOLTIP'         => 'Zur Zeit nicht implementiert',
    'FCKUSTOM_ENABLE_PRE_FILLING_TOOLTIP'              => 'Aktivieren Sie das automatische Ausfüllen des Kustom Checkout Iframes durch die Daten des im OXID eShop eingeloggten Kunden',
    'FCKUSTOM_ENABLE_PREFILL_NOTIFICATION_TOOLTIP'     => 'Wenn das automatische Ausfüllen des Kustom Checkout Iframes aktiv ist, muss für manche Länder ein entsprechender Datenschutz-Hinweis eingeblendet werden. Dieser Hinweis wird durch diesen Schalter aktiviert.',
    'FCKUSTOM_TERMS_AND_CONDITIONS_URL_TOOLTIP'        => 'Geben Sie hier die URL zu Ihren Allgemeinen Geschäftsbedingungen an. Diese werden im Kustom Checkout Iframe verlinkt. Eine gültige URL, die mit https:// beginnt, muss angegeben werden.',
    'FCKUSTOM_CANCELLATION_RIGHTS_URL_TOOLTIP'         => 'Geben Sie hier die URL zu Ihrer Webseite mit der Erklärung zum Widerrufsrecht an. Die URL muss mit https:// beginnen.',
    'FCKUSTOM_SHIPPING_DETAILS_TOOLTIP'                => 'Diese Versandhinweise werden dem Kunden auf der Danke-Seite nach Abschluss der Bestellung angezeigt.',
    'FCKUSTOM_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'    => 'Ordnen Sie diese externe Bezahlart einer der vordefinierten Zahlungsarten zu',
    'FCKUSTOM_ENABLE_EXTERNAL_PAYMENT_TOOLTIP'         => 'Mit diesem Schalter aktivieren Sie diese Zahlungsart als externe Bezahlart für den Kustom Checkout. Wenn aktiv, kann der Kunde diese Zahlungsart aus der Liste der Zahlungsarten im Kustom Checkout Iframe auswählen.',
    'FCKUSTOM_ENABLE_EXTERNAL_CHECKOUT_TOOLTIP'        => 'Mit diesem Schalter aktivieren Sie diese Zahlungsart als externen Checkout. Wenn aktiv, wird diese Zahlungsart schon vor der Eingabe von Kundendaten ganz unten im Kustom Checkout Iframe angezeigt.',
    'FCKUSTOM_EXTERNAL_PAYMENT_IMAGE_URL_TOOLTIP'      => 'Geben Sie hier die URL zu einem Bild an, das neben der Zahlungsart im Kustom Checkout Iframe eingeblendet werden soll. Verwenden Sie optimalerweise ein Bild von einer sicheren URL, die mit https:// beginnt.',
    'FCKUSTOM_EXTERNAL_CHECKOUT_IMAGE_URL_TOOLTIP'     => 'Geben Sie hier die URL zu einem Bild an, das als Button für diese Zahlungsart im Kustom Checkout Iframe unten eingeblendet werden soll. Verwenden Sie optimalerweise ein Bild von einer sicheren URL, die mit https:// beginnt.',
    'FCKUSTOM_EXTERNAL_IMAGE_URL_EMPTY'                => 'Bitte geben Sie für alle Sprachen eine URL an',
    'FCKUSTOM_EXTERNAL_IMAGE_URL_INVALID'              => 'Bitte geben Sie eine gültige URL an, die mit https:// beginnt',
    'FCKUSTOM_EMD_CUSTOMER_INFO_TOOLTIP'               => 'Dieser Schalter aktiviert die Übertragung zusätzlicher Daten an Kustom, in diesem Falle die Customer Account Info, darin ist das Datum der Registrierung des Kundenkontos und dessen letzte Veränderung enthalten.',
    'FCKUSTOM_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'        => 'Dieser Schalter aktiviert die Übertragung zusätzlicher Daten an Kustom, in diesem Falle die Payment History Full, darin sind die bisherigen Einkäufe des Kunden enthalten.',
    'FCKUSTOM_EMD_PAYMENT_TYPE_TOOLTIP'                => 'Ordnen Sie bitte zu, um was für eine Zahlungsart es sich bei dieser Bezahlmethode handelt.',
    'FCKUSTOM_EMD_HISTORY_FULL_TOOLTIP'                => 'Bitte legen Sie hier fest, ob und ggf. welche Bestellungen mit dieser Zahlungsart bei der Übertragung der Bestellhistorie des Kunden enthalten sein sollen. Die Abhängigkeit des Feldes OXORDER.OXPAID besagt, ob dabei nur bezahlte oder alle Bestellungen berücksichtigt werden sollen.',
    'FCKUSTOM_EMD_PASSTHROUGH_FIELD_TOOLTIP'           => 'Es besteht die Möglichkeit mit Hilfe eines Pass-through Feldes weitere beliebige Daten an Kustom zu übermitteln. Um diese Funktion zu nutzen, müssen Sie ein entsprechendes Modul im OXID eShop installieren, dass die gewünschten Daten in das Pass-through Feld schreibt. Eine entsprechende Anleitung finden Sie in der Entwickler-Dokumentation.',
    'FCKUSTOM_DISPLAY_ON_HOME_TOOLTIP'                 => 'Mit diesem Schalter aktivieren Sie einen Kustom Banner auf Ihrer Shop-Startseite in den Standard-Themes Flow bzw. Wave.',
    'FCKUSTOM_BANNER_SRC_TOOLTIP'                      => 'Hier können Sie den script-Tag für die Banner-Einbindung hinterlegen. Im Banner-Portal von Kustom finden Sie ggf. weitere Banner zur Auswahl.',
    'FCKUSTOM_FOOTER_PAYMENT_METHODS_TOOLTIP'          => 'Mit diesem Schalter aktivieren Sie das Kustom Payment Method Display im Footer Ihres Shops in den Standard-Themes Flow bzw. Wave.',
    'FCKUSTOM_FOOTER_KUSTOM_LOGO_TOOLTIP'              => 'Mit diesem Schalter fügen Sie das Kustom Logo im Footer Ihres Shops in den Standard-Themes Flow bzw. Wave ein.',
    'FCKUSTOM_BORDER_TOOLTIP'                          => 'Farbe des Rahmens, der im Falle verschiedener zur Verfügung stehender Unter-Optionen nach Auswahl der Kustom Zahlungsart im Shop-Frontend erscheint.',
    'FCKUSTOM_BORDER_SELECTED_TOOLTIP'                 => 'Farbe des Rahmens, der im Falle verschiedener zur Verfügung stehender Unter-Optionen nach Auswahl der Kustom Zahlungsart im Shop-Frontend erscheint. Dieser Farbwert wird zur Hervorhebung der zur Zeit aktiv ausgewählten Unter-Option verwendet.',
    'FCKUSTOM_BUTTON_TOOLTIP'                          => 'Diese Einstellung hat zum Zeitpunkt der Veröffentlichung dieses Moduls noch keine Auswirkung.',
    'FCKUSTOM_BUTTON_TEXT_TOOLTIP'                     => 'Diese Einstellung hat zum Zeitpunkt der Veröffentlichung dieses Moduls noch keine Auswirkung.',
    'FCKUSTOM_DESIGN_CHECKBOX_TOOLTIP'                 => 'Hintergrundfarbe der Radio-Buttons, die im Falle verschiedener zur Verfügung stehender Unter-Optionen nach Auswahl der Kustom Zahlungsart im Shop-Frontend erscheinen',
    'FCKUSTOM_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'       => 'Diese Einstellung hat zum Zeitpunkt der Veröffentlichung dieses Moduls noch keine Auswirkung.',
    'FCKUSTOM_DETAILS_TOOLTIP'                         => 'Farbe der Aufzählungszeichen bei der Darstellung der Zahlungs-Details auf der Zahlungsarten-Auswahlseite.',
    'FCKUSTOM_HEADER_TOOLTIP'                          => 'Diese Einstellung hat zum Zeitpunkt der Veröffentlichung dieses Moduls noch keine Auswirkung.',
    'FCKUSTOM_LINK_TOOLTIP'                            => 'Farbe der Links innerhalb der Detail-Beschreibung der Zahlungsarten auf der Zahlungsarten-Auswahlseite.',
    'FCKUSTOM_TEXT_TOOLTIP'                            => 'Textfarbe der Detail-Beschreibung der Zahlungsarten auf der Zahlungsarten-Auswahlseite.',
    'FCKUSTOM_SECONDARY_TEXT_TOOLTIP'                  => 'Alternative Textfarbe der Detail-Beschreibung der Zahlungsarten auf der Zahlungsarten-Auswahlseite.',
    'FCKUSTOM_BORDER_RADIUS_TOOLTIP'                   => 'Mit dieser Einstellung können Sie den Grad der Rundung des Rahmens festlegen, der im Falle verschiedener zur Verfügung stehender Unter-Optionen nach Auswahl der Kustom Zahlungsart im Shop-Frontend erscheint.',

    'KUSTOM_ONLY_FOR_KUSTOM_PAYMENT'         => 'Dieser Reiter betrifft nur Kustom Bestellungen',
    'KUSTOM_CAPTURE_FULL_ORDER'              => 'Komplette Bestellung capturen',
    'KUSTOM_CAPTURE_ID'                      => 'Abbuchungs-ID',
    'KUSTOM_CAPTURE_REFERENCE'               => 'Kustom Referenz',
    'KUSTOM_CAPTURE_AMOUNT'                  => 'Abbuchungs-Betrag',
    'KUSTOM_CAPTURE_DATE'                    => 'Abgebucht am',
    'KUSTOM_REFUND_AMOUNT'                   => 'Erstattungsbetrag',
    'KUSTOM_REFUND_DESCRIPTION'              => 'Erstattung Erläuterung',
    'KUSTOM_REFUND_DATE'                     => 'Erstattet am',
    'KUSTOM_CAPTURES'                        => 'Abbuchungen',
    'KUSTOM_REFUNDS'                         => 'Erstattungen',
    'KUSTOM_CANCEL_ORDER'                    => 'Bestellung stornieren',
    'KUSTOM_ORDER_IS_CANCELLED'              => 'Die Bestellung wurde storniert. ',
    'KUSTOM_SEE_ORDER_IN_PORTAL'             => '<a href="%s" target="_blank" class="alert-link">Diese Bestellung im Kustom Portal aufrufen</a>',
    'KUSTOM_ORDER_NOT_IN_SYNC'               => '<strong>Achtung!</strong> Die Daten dieser Bestellung weichen von den bei Kustom gespeicherten Daten ab. ',
    'FCKUSTOM_ORDER_UPDATE_CANT_BE_SENT_TO_KUSTOM' => 'Achtung! Aufgrund des aktuellen Bestellstatus kann diese Anpassung nicht an Kustom übermittelt werden. Führen Sie die entsprechende Anpassung ggf. direkt im Kustom Merchant Portal von Hand durch.',
    'FCKUSTOM_ORDER_UPDATE_REJECTED_BY_KUSTOM'     => 'Achtung! Ihre letzten Änderungen an dieser Bestellung konnten nicht von Kustom verarbeitet werden (Grund: %s). Bitte machen Sie Ihre kürzlichen Änderungen im OXID eShop rückgängig oder führen Sie die entsprechende Anpassung von Hand im Kustom Merchant Portal durch falls erforderlich.',
    'KUSTOM_UNAUTHORIZED_REQUEST'            => 'Unerlaubte Anfrage. Prüfen Sie die Einstellungen des Kustom Moduls und die Merchant ID sowie das zugehörige Passwort',
    'KUSTOM_ORDER_NOT_FOUND'                 => 'Diese Bestellung konnte bei Kustom im System nicht gefunden werden. Änderungen an den Bestelldaten werden daher nicht an Kustom übertragen.',
    'KUSTOM_GENERAL_ERROR'                   => 'Ein unbekannter Fehler ist aufgetreten. Die Anfrage konnte nicht bearbeitet werden.',
    'KUSTOM_MID_CHANGED_FOR_COUNTRY'         => '<strong>Wrong credentials!</strong> This order has been placed using <strong>%s</strong> merchant id. Currently configured merchant id for <strong>%s</strong> is <strong>%s</strong>.',
    'FCKUSTOM_PRODUCT_NAME'                        => 'Produktname',
    'FCKUSTOM_ANONYMIZED_PRODUCT'                  => 'Anonymisierter Produkttitel:',
    'FCKUSTOM_KCO_INVOICE_MSG'                     => 'Die Zahlung wird durch unseren Partner Kustom abgewickelt. Bitte beachten Sie die von Kustom versandten Zahlungsinformationen, falls Sie den Einkauf noch nicht bezahlt haben. Sie können all Ihre Einkäufe über Kustom.com bzw. die Kustom App verwalten und sogar mit nur einem Klick bezahlen.',
    'FCKUSTOM_VOUCHER_DISCOUNT'                    => 'Gutschein Rabatt',

    'FCKUSTOM_KCO_BUTTON_TOOLTIP'                    => 'Hintergrundfarbe des Bezahl-Buttons innerhalb des Kustom Checkout Iframes.',
    'FCKUSTOM_KCO_BUTTON_TEXT_TOOLTIP'               => 'Farbe des Textes des Bezahl-Buttons im Kustom Checkout Iframe.',
    'FCKUSTOM_KCO_DESIGN_CHECKBOX_TOOLTIP'           => 'Hintergrundfarbe der Checkboxen innerhalb des Kustom Checkout Iframes.',
    'FCKUSTOM_KCO_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP' => 'Farbe des Checkbox-Hakens innerhalb von Checkboxen im Rahmen des Kustom Checkout Iframes.',
    'FCKUSTOM_KCO_HEADER_TOOLTIP'                    => 'Farbe der Überschriften / Titel innerhalb des Kustom Checkout Iframes.',
    'FCKUSTOM_KCO_LINK_TOOLTIP'                      => 'Farbe der Links innerhalb des Kustom Checkout Iframes.',
    'FCKUSTOM_KCO_BORDER_RADIUS_TOOLTIP'             => 'Mit dieser Einstellung können Sie den Grad der Rundung des Rahmens des Kustom Checkout Iframes festlegen.',

    'FCKUSTOM_GIFT_WRAPPING_TITLE' => 'Geschenkverpackung',
    'FCKUSTOM_GIFT_CARD_TITLE'     => 'Grußkarte',

    'FCKUSTOM_ERROR_SHOP_SSL_NOT_CONFIGURED' => 'Fataler Fehler: Die Angabe einer gültigen SSL-geschützten (https) $this->sSSLShopURL in der config.inc.php Ihres Shops ist Pflicht, wenn Sie den %s aktivieren möchten!',
    'FCKUSTOM_ERROR_WRONG_CREDS'             => '<strong>Falsche Zugangsdaten!</strong>',
    'FCKUSTOM_ERROR_KCO_INACTIVE'            => 'Setup-Fehler: Kustom Checkout ist im Shop nicht aktiv',

    'KUSTOM_CAPTURE_SUCCESSFULL'            => 'Der Betrag wurde erfolgreich abgebucht.',
    'FCKUSTOM_CAPUTRE_FAIL_ORDER_CANCELLED' => ' Die Bestellung konnte nicht abgebucht werden, da sie bereits storniert wurde.',
    'FCKUSTOM_ANONYMIZED_PRODUCT_TOOLTIP'   => 'Geben Sie hier die Zeichenfolge ein, die anstatt des tatsächlichen Produkttitels an Kustom gesendet werden soll.',
    'FCKUSTOM_NO_REQUESTS_WILL_BE_SENT'     => 'Ihre Änderungen an dieser Bestellung werden nicht an Kustom übertragen.',
    'FCKUSTOM_USER_GUIDE'                   => 'Benutzerhandbuch',
    'FCKUSTOM_REGISTER_NOW_BUTTON'          => 'Registrieren',
    'FCKUSTOM_LEARN_MORE_BUTTON'            => 'Mehr erfahren',

    'FCKUSTOM_CUSTOMER_TYPE'         => 'Unterstützte Kundenarten',
    'FCKUSTOM_CUSTOMER_TYPE_TOOLTIP' => 'Hier können Sie einstellen, ob der Shop ausschließlich B2C Transaktionen (Standard-Einstellung). nur B2B Transaktionen oder sowohl B2C als auch B2B Transaktionen akzeptieren soll. <br> Hinweis: Nach dem Umstellen der Kundenarten muss der Session cache des Browsers gelöscht werden, damit die Bezahlung getestet werden kann.',
    'FCKUSTOM_B2C'                   => 'Nur B2C Kunden',
    'FCKUSTOM_B2B'                   => 'Nur B2B Kunden',
    'FCKUSTOM_B2B_B2C'               => 'Hauptsächlich B2B Kunden, aber auch B2C Kunden',
    'FCKUSTOM_B2C_B2B'               => 'Hauptsächlich B2C Kunden, aber auch B2B Kunden',
    'FCKUSTOM_NEED_SUPPORT'          => 'Benötigen Sie Hilfe bei der Integration?',
    'FCKUSTOM_REACH_SUPPORT'         => 'Kontaktieren Sie Kustom‘s Merchant Support',

    'FCKUSTOM_EU_WARNING' => '<p>Um mit der EU Geoblocking Verordnung übereinzustimmen, wird dringend empfohlen, alle europäischen Länder zu aktivieren und der Bezahlmethode Kustom Checkout zuzweisen.</p><p>Es fehlen folgende Länder: %s</p>',


    'FCKUSTOM_IS_ENABLED_HEADLINE' => 'Kustom Instant Shopping aktivieren',
    'FCKUSTOM_IS_ENABLED' => 'Aktiv',
    'FCKUSTOM_IS_BUTTON_REPLACE' => 'Button Key erneuern',
    'FCKUSTOM_IS_REPLACE' => 'Neuen Button Key erzeugen',
    'FCKUSTOM_IS_BUTTON_REPLACE_TOOLTIP' => 'Sie können den Button Key aktualisieren, wenn Konfigurations- oder Identifikationsdaten auf Seiten von Kustom eine Änderung erforderlich machen. Normalerweise können Sie einen einmal erzeugten Button Key so lange verwenden wie Sie möchten.',
    'FCKUSTOM_IS_ENABLED_TOOLTIP' => 'Schalten Sie hier Kustom Instant Shopping an. Dadurch wird automatisch ein Button Key für die Verwendung im Shop Frontend erzeugt.',
    'FCKUSTOM_IS_BUTTON_APEARANCE_HEADLINE' => 'Button Styling Einstellungen',
    'FCKUSTOM_IS_VARIATION_TOOLTIP' => 'Bitte wählen Sie zwischen einem vollständig im Kustom Look gebrandeten Button und einer neutraleren Light Variante.',
    'FCKUSTOM_IS_TAGLINE_TOOLTIP' => 'Bitte wählen Sie, ob die Schriftfarbe der Tagline unterhalb des Buttons hell oder dunkel sein soll.',
    'FCKUSTOM_IS_TYPE_TOOLTIP' => 'Bitte wählen Sie die gewünschte Beschriftung des Buttons.',
    'FCKUSTOM_IS_BUTTON_PREVIEW' => 'Vorschau des Buttons',
    'FCKUSTOM_IS_BUTTON_PLACEMENT_DETAILS' => 'Auf Artikeldetailseite anzeigen',
    'FCKUSTOM_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP' => 'Aktivieren Sie diese Funktion, damit der Kustom Instant Shopping Button auf allen Artikeldetailseiten in Ihrem Shop eingeblendet wird.',
    'FCKUSTOM_IS_BUTTON_PLACEMENT_BASKET' => 'Auf der Warenkorb Übersicht anzeigen',
    'FCKUSTOM_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP' => 'Aktivieren Sie diese Funktion, damit der Kustom Instant Shopping Button auf der Warenkorb Übersicht in Ihrem Shop eingeblendet wird.',
    'FCKUSTOM_IS_BUTTON_SETTINGS_HEADLINE' => 'Weitere Instant Shopping Einstellungen',
    'FCKUSTOM_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS' => 'Lieferanschrift darf von Rechnungsanschrift abweichen',
    'FCKUSTOM_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP' => 'Falls die Lieferung an eine abweichende Lieferanschrift ermöglicht werden soll, aktivieren Sie diesen Schalter.',
    'FCKUSTOM_IS_SETTING_DATE_OF_BIRTH_MANDATORY' => 'Geburtsdatum als Pflichtfeld',
    'FCKUSTOM_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP' => 'Falls Sie die Angabe eines Geburtsdatums zwingend erfordern wollen, aktivieren Sie diesen Schalter. Normalerweise ist für Kustom das Geburtsdatum kein Pflichtfeld. Allerdings ist die Angabe notwendig, um den Kauf auf Rechnung oder eine Ratenzahlung zu ermöglichen.',
    'FCKUSTOM_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY' => 'Nationale ID Nummer als Pflichtfeld',
    'FCKUSTOM_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP' => 'Bitte wählen Sie, ob die nationalie Identifikationsnummer ein Pflichtfeld sein soll.',
    'FCKUSTOM_IS_BUTTON_SETTINGS_VARIATION' => 'Variation',
    'FCKUSTOM_IS_BUTTON_SETTINGS_TAGLINE' => 'Tagline',
    'FCKUSTOM_IS_BUTTON_SETTINGS_TYPE' => 'Type',
    'FCKUSTOM_IS_SETTING_PHONE_MANDATORY' => 'Telefonnummer ist Pflichtfeld',
    'FCKUSTOM_IS_SETTING_PHONE_MANDATORY_TOOLTIP' => 'Bitte wählen Sie, ob die Telefonnummer ein Pflichtfeld sein soll.',
    'FCKUSTOM_IS_DEFAULT_COUNTRY_TIP'            => 'Bitte wählen Sie aus der Liste aus, welches Land bei Aufruf des Kustom Instant Shoppings standardmäßig voreingestellt sein soll, solange der Kunde sein Land noch nicht angegeben hat.',
    'FCKUSTOM_IS_TERMS_URI_TIP' => 'Geben Sie hier die URL zu Ihren Allgemeinen Geschäftsbedingungen an. Diese werden im Kustom Instant Shopping Popup verlinkt. Eine gültige URL, die mit https:// beginnt, muss angegeben werden.',
    'FCKUSTOM_SHIPPING_KCO' => 'Versandarten-Zuordnung für den Kustom Checkout',
    'FCKUSTOM_SHIPPING_KCO_DESC' => 'Bitte ordnen Sie Ihren definierten Versandarten die entsprechenden Kustom Bezeichnungen zu. Über diese Zuordnung richten Sie unter anderem die Lieferung an Packstationen ein.',
    'FCKUSTOM_SHIPPING_SETTINGS' => 'Versandarten',
    'FCKUSTOM_COMPLETE_REFUND' => 'Komplette Bestellung gutschreiben',
    'FCKUSTOM_PACKSTATION_NO_SHIPPING_SET' => 'Keine aktiven Versandarten gefunden',

    'FCKUSTOM_AUTHPAYMENTMETHOD'                       => 'Verwendete Zahlart: ',
    'FCKUSTOM_AUTHPAYMENTMETHOD_unknown'               => 'Kustom',
    'FCKUSTOM_AUTHPAYMENTMETHOD_pay_by_card'           => 'Kreditkarte',
    'FCKUSTOM_AUTHPAYMENTMETHOD_direct_debit'          => 'Lastschrift',
    'FCKUSTOM_AUTHPAYMENTMETHOD_direct_bank_transfer'  => 'Sofortüberweisung',
    'FCKUSTOM_AUTHPAYMENTMETHOD_slice_it_by_card'      => '3 zinsfreie Raten',
    'FCKUSTOM_AUTHPAYMENTMETHOD_fixed_sum_credit'      => 'Finanzierung',
    'FCKUSTOM_AUTHPAYMENTMETHOD_b2b_invoice'           => 'B2B Rechnung (Billie)',
    'FCKUSTOM_AUTHPAYMENTMETHOD_invoice'               => 'Rechnung',
    'FCKUSTOM_AUTHPAYMENTMETHOD_pay_later_by_card'     => 'Kartenzahlung in 30 Tagen',
);
