<?php
/**
 * Copyright 2018 Kustom AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset' => 'UTF-8',

    'FCKUSTOM_KUSTOMMAINMENU'      => 'Kustom',
    'FCKUSTOM_START'               => 'Start',
    'FCKUSTOM_GENERAL_SETTINGS'    => 'General Settings',
    'FCKUSTOM_CONFIGURATION'       => 'Configuration',
    'FCKUSTOM_CONFIGURATION_KCO'   => 'Configuration for Kustom Checkout',
    'FCKUSTOM_KUSTOMDESIGN'        => 'Design Settings',
    'FCKUSTOM_EXTERNAL_PAYMENTS'   => 'External Payment Methods',
    'FCKUSTOM_EXTRA_MERCHANT_DATA' => 'Extra Merchant Data',
    'FCKUSTOM_BASIC_SETTINGS'      => 'basic settings',
    'FCKUSTOM_DISCOUNT_TITLE'      => 'Discount',
    'FCKUSTOM_MERCHANT_SUPPORT'    => 'Merchant Support',

    'fckustom_tbclkustom_orders'     => 'Kustom',
    'FCKUSTOM_NO_OPTIONS_MODE'       => 'There is no options available in this mode.',
    'FCKUSTOM_CHANGES_SAVED'         => 'All changes have been saved.',
    'FCKUSTOM_EMPTY_FIELDS_WARRNING' => 'Leaving url fields empty may lead to module malfunction.',

    'FCKUSTOM_EASY'                         => 'It is easy to integrate Kustom',
    'FCKUSTOM_PHONE'                        => 'Phone',
    'FCKUSTOM_EMAIL'                        => 'Email',
    'FCKUSTOM_BUSINESS_HOURS'               => 'Business hours',
    'FCKUSTOM_MONDAY'                       => 'Mo',
    'FCKUSTOM_TUESDAY'                      => 'Tue',
    'FCKUSTOM_WEDNESDAY'                    => 'Wed',
    'FCKUSTOM_THURSDAY'                     => 'Thu',
    'FCKUSTOM_FRIDAY'                       => 'Fri',
    'FCKUSTOM_SATURDAY'                     => 'Sat',
    'FCKUSTOM_SUNDAY'                       => 'Sun',
    'FCKUSTOM_YOUR_COUNTRY_SPECIFIC_CREDS'  => 'Your country specific credentials',
    'FCKUSTOM_ADD_COUNTRY_SPECIFIC_CREDS'   => 'Add country specific credentials',
    'FCKUSTOM_COUNTRY'                      => 'Country',
    'FCKUSTOM_MERCHANT_ID'                  => 'Merchant ID/API Ussername',
    'FCKUSTOM_PASSWORD'                     => 'Password/API Password',
    'FCKUSTOM_DEFAULT_SHOP_COUNTRY'         => 'Default Shop Country',
    'FCKUSTOM_ENABLE_LOGGING'               => 'Enable logging',
    'FCKUSTOM_SEND_ADDITIONAL_PRODUCT_DATA' => 'Send additional product data to Kustom?',
    'FCKUSTOM_PRODUCT_URLS'                 => 'Product URLs',
    'FCKUSTOM_IMAGE_URLS'                   => 'Image URLs',
    'FCKUSTOM_ENABLE_ANONYMIZATION'         => 'Enable anonymization',
    'FCKUSTOM_ADD'                          => 'Add',

    'FCKUSTOM_CHECKOUT_NAME'             => 'Kustom Checkout',

    'FCKUSTOM_CHECKOUT_DESC' => 'A full checkout solution embedded on your site. It lets your customers check out on 
    your site simply with their email and zip, and pay with the major payment methods. 
    All available in one integration.',

    'FCKUSTOM_PAYMENTS_DESC' => 'Kustom offers three payment solutions. Pay now, Pay later and Financing. This allows your consumers to try before they buy, finance purchases in your store, or make use of other payment options made available by Kustom.',
    'FCKUSTOM_EASY_AND_SECURE_SHOPPING' => 'Kustom, formerly Kustom Checkout, is one of Europe’s leading checkout solutions. Quick to integrate, easy to run.',
    'FCKUSTOM_WELCOME_TO_CONFIGURATION' => 'Welcome to Kustom’s confi guration section. Click on the Kustom sub-categories to complete the installation of this module.',

    'FCKUSTOM_CREATE_USER_ACCOUNT'               => 'Create Customer Account',
    'FCKUSTOM_SUBSCRIBE_TO_NEWSLETTER'           => 'Subscribe to Newsletter',
    'FCKUSTOM_CREATE_USER_ACCOUNT_AND_SUBSCRIBE' => 'Create Customer Account AND subscribe to Newsletter',
    'FCKUSTOM_NO_CHECKBOX'                       => 'Do not show a Checkbox',

    'FCKUSTOM_DISPLAY_ON_HOME'        => 'Display on shop homepage?',
    'FCKUSTOM_BANNER_SRC'             => 'Kustom Banner Source',
    'FCKUSTOM_FOOTER'                 => 'Footer',
    'FCKUSTOM_DISPLAY_IN_FOOTER'      => 'What to display in footer?',
    'FCKUSTOM_FOOTER_PAYMENT_METHODS' => 'Payment Method Display',
    'FCKUSTOM_FOOTER_KUSTOM_LOGO'     => 'Kustom Logo',
    'FCKUSTOM_DESIGN'                 => 'Design',
    'FCKUSTOM_LONG_VERSION'           => 'Long Version:',
    'FCKUSTOM_SHORT_VERSION'          => 'Short Version:',
    'FCKUSTOM_DETAILS_AND_BASKET'     => 'Product details page',
    'FCKUSTOM_DISPLAY_PAYMENT_WIDGET' => 'Display Kustom Payment Method Widget?',
    'FCKUSTOM_KCO_SHIPPINGMETHOD'     => 'Kustom Checkout Delivery Method',
    'FCKUSTOM_ON_BASKET_PAGE'         => 'On basket page',
    'FCKUSTOM_PAYMENT_DESIGN'         => 'Kustom Payment Design Options',
    'FCKUSTOM_CHECKOUT_DESIGN'        => 'Kustom Checkout Design Options',
    'FCKUSTOM_COLOR_SETTINGS'         => 'Color settings:',
    'FCKUSTOM_BORDER'                 => 'Border:',
    'FCKUSTOM_BORDER_SELECTED'        => 'Border selected:',
    'FCKUSTOM_BUTTON'                 => 'Button:',
    'FCKUSTOM_BUTTON_TEXT'            => 'Button text:',
    'FCKUSTOM_CHECKBOX'               => 'Checkbox:',
    'FCKUSTOM_CHECKBOX_CHECKMARK'     => 'Checkbox Checkmark:',
    'FCKUSTOM_DETAILS'                => 'Details:',
    'FCKUSTOM_HEADER'                 => 'Header:',
    'FCKUSTOM_LINK'                   => 'Link:',
    'FCKUSTOM_TEXT'                   => 'Text:',
    'FCKUSTOM_SECONDARY_TEXT'         => 'Secondary Text:',
    'FCKUSTOM_RADIUS_SETTINGS'        => 'Radius settings:',
    'FCKUSTOM_BORDER_RADIUS'          => 'Border radius:',

    'FCKUSTOM_ALLOW_SEPARATE_SHIPPING_ADDRESS'   => 'Allow separate shipping address',
    'FCKUSTOM_PHONE_NUMBER_MANDATORY'            => 'Phone number mandatory',
    'FCKUSTOM_DATE_OF_BIRTH_MANDATORY'           => 'Date of birth mandatory',
    'FCKUSTOM_ENABLE_AUTOFOCUS'                  => 'Enable autofocus on Kustom Checkout iframe',
    'FCKUSTOM_ADD_A_CUSTOM_CHECKBOX'             => 'Add  custom checkbox to Kustom Checkout iframe',
    'FCKUSTOM_ENABLE_DHL_PACKSTATION'            => 'Enable shipping to DHL Packstation',
    'FCKUSTOM_ENABLE_PRE_FILLING'                => 'Enable Pre-filling',
    'FCKUSTOM_ENABLE_PREFILL_NOTIFICATION'       => 'Enable Pre-filling notification',
    'FCKUSTOM_SALUTATION_MANDATORY'              => 'Salutation mandatory',
    'FCKUSTOM_SET_TAC_URI'                       => 'Set terms and conditions URI - mandatory',
    'FCKUSTOM_SET_CANCEL_URI'                    => 'URL for Cancellation rights - mandatory ',
    'FCKUSTOM_SHIPPING_DETAILS'                  => 'URL for Shipping details - mandatory',
    'FCKUSTOM_NO_VALIDATION_NEEDED'              => 'No validation',
    'FCKUSTOM_VALIDATION_IGNORE_TIMEOUTS_NEEDED' => 'Perform validation, but ignore validation timeouts',
    'FCKUSTOM_SUCCESSFUL_VALIDATION_NEEDED'      => 'Require successful validation',
    'FCKUSTOM_ORDER_VALIDATION'                  => 'Order validation',

    'FCKUSTOM_KUSTOM.'           => 'Kustom (formerly Kustom Checkout)',
    'FCKUSTOM_KUSTOM_START'      => 'Entwickelt, um den Einkauf für Käufer zum Kinderspiel zu machen, völlig flexibel an Ihre Bedürfnisse anzupassen und überraschend einfach zu bedienen.',
    'FCKUSTOM_TRUSTED.'          => 'A trusted and seamless experience',
    'FCKUSTOM_TRUSTED_START'     => 'Checking out should feel effortless. With a mobile-fi rst experience, address pre-fi ll and express checkout, your shoppers breeze through the purchase — helping you reduce drop-offs and bring them back.',
    'FCKUSTOM_WAY.'              => 'Let your shoppers pay their way',
    'FCKUSTOM_WAY_START'         => 'Give shoppers the flexibility to pay now or later, with the payment method they prefer. No matter where you sell, Kustom supports all the popular options like cards, Kustom, bank transfers, Swish, Apple Pay, MobilePay and more, so you drive conversion in every market."',
    'FCKUSTOM_QUICK'             => 'Quick to integrate, easy to run',
    'FCKUSTOM_QUICK_START'       => 'Launch and scale easily with one integration for payments, shipping, markets and currencies.',
    'FCKUSTOM_CHECKOUT'          => 'Kustom‘s Checkout.',
    'FCKUSTOM_CHECKOUT_START'    => 'The best checkout experience for your customers. Reliable customer identification and shipping selection. All payments including worldwide availability, locally optimized. We take all the risk and you always get your money.',

    'FCKUSTOM_RB_HOW_TO_ACTIVATE'             => 'How-to-activate<br>Kustom guide.',
    'FCKUSTOM_RB_HOW_TO_ACTIVATE_LIST_ONE'    => 'In the OXID backend click on the new menu item Kustom, the sub-category “General Settings”, and enter your access data (user name and password) and make the OXID-typical assignments for payment methods under Shop settings > Payment methods and > Shipping methods',
    'FCKUSTOM_RB_HOW_TO_ACTIVATE_LIST_TWO'    => 'Save the changes.',
    'FCKUSTOM_RB_HOW_TO_ACTIVATE_LIST_THREE'  => 'You are now online and you can start selling with Kustom.',
    'FCKUSTOM_RB_MERCHANT_SUPPORT'            => 'Merchant support',
    'FCKUSTOM_DEVICE_IMG'                    => 'device.png',

    'FCKUSTOM_EXTERNAL_PAYMENTS_ADMIN_DESC'   =>
        'Here you can configure External Payment Methods and External Checkouts to be included inside the Kustom Checkout Iframe. 
        For a detailed description of the different settings please see the tool-tip function 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-ku" href="https://github.com/FATCHIP-GmbH/kustom-checkout-oxid7/wiki" target="_blank">documentation</a> 
or contact Kustom support.',
    'FCKUSTOM_EXTRA_MERCHANT_DATA_ADMIN_DESC' => 'Here you can configure the Extra Merchant Data to use with the Kustom extension 
for OXID. For a detailed description of the different settings please see the tool-tip function 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-ku" href="https://github.com/FATCHIP-GmbH/kustom-checkout-oxid7/wiki" target="_blank">documentation</a> 
or contact Kustom support.',
    'FCKUSTOM_DESIGN_SETTINGS_ADMIN_DESC'     => 'Here you can configure the Design Settings to use with the Kustom extension 
for OXID. For a detailed description of the different settings please see the tool-tip function 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-ku" href="https://github.com/FATCHIP-GmbH/kustom-checkout-oxid7/wiki" target="_blank">documentation</a> 
or contact Kustom support.',
    'FCKUSTOM_GENERAL_SETTINGS_ADMIN_DESC'    => 'For a detailed description of the different settings please see the tool-tip function
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-ku" href="https://github.com/FATCHIP-GmbH/kustom-checkout-oxid7/wiki" target="_blank">documentation</a> or contact Kustom support.',
    'FCKUSTOM_CONFIGURATION_KCO_ADMIN_DESC'   => 'On this page you can configure the Kustom Checkout specific settings. 
For a detailed description of the different settings please see the tool-tip function 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, see the <a class="cl-ku" href="https://github.com/FATCHIP-GmbH/kustom-checkout-oxid7/wiki" target="_blank">documentation</a> 
or contact Kustom support.',

    'FCKUSTOM_PAYMENT_METHOD'          => 'Payment method',
    'FCKUSTOM_EXTERNAL_PAYMENT_METHOD' => 'External Payment Method',
    'FCKUSTOM_EXTERNAL_CHECKOUT'       => 'External Checkout',
    'FCKUSTOM_IMAGE_URI_EXT_PAYMENT'   => 'Image URI external payment method',
    'FCKUSTOM_IMAGE_URI_EXT_CHECKOUT'  => 'Image URI external checkout',
    'FCKUSTOM_IMAGE_TIP_69x24'         => 'Dimensions: 69x24 Pixel',
    'FCKUSTOM_IMAGE_TIP_276x48'        => 'Dimensions: 276x48 Pixel',
    'FCKUSTOM_USER_GUIDE_DESCRIPTION'  => 'View the user manual for the Kustom module for OXID eShop here.',
    'FCKUSTOM_USER_GUIDE_LINK'         => 'https://github.com/FATCHIP-GmbH/kustom-checkout-oxid7/wiki',
    'FCKUSTOM_USER_GUIDE_BUTTON'         => 'User guide',

    'FCKUSTOM_CHOOSE' => 'Choose',

    'FCKUSTOM_CUSTOMER_ACCOUNT_INFO' => 'Customer account info',
    'FCKUSTOM_PAYMENT_HISTORY_FULL'  => 'Payment history full',
    'FCKUSTOM_PASSTHROUGH_FIELD'     => 'Pass-through field',

    'FCKUSTOM_ASSIGN_PAYMENT_METHOD_TYPE'           => 'Assign corresponding payment method type:',
    'FCKUSTOM_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY' => 'Which orders should be considered in Payment history full?',
    'FCKUSTOM_EMD_ORDER_HISTORY_ALL'                => 'All orders independent of oxpaid date',
    'FCKUSTOM_EMD_ORDER_HISTORY_PAID'               => 'All orders with filled oxpaid date; ignore unpaid orders',
    'FCKUSTOM_EMD_ORDER_HISTORY_NONE'               => 'Ignore all orders paid by this payment method',
    'FCKUSTOM_OTHER_PAYMENT'                        => 'Other payment option',
    'FCKUSTOM_DIRECT_BANKING'                       => 'Direct banking',
    'FCKUSTOM_CARD'                                 => 'Card',

    'FCKUSTOM_TEST_MODE_TOOLTIP'                       => 'Choose between Playground (test mode) and Live (productive mode). Only switch to productive operation after successfully performing integration tests and after consulting with your Kustom Integration Manager.',
    'FCKUSTOM_GLOBAL_MERCHANT_ID_TOOLTIP'              => 'Please enter your Kustom Merchant ID here. You received it in the welcome email from Kustom. This merchant ID and password apply globally to all countries. Only if you have received different Merchant IDs for different countries, you can add country-specific access data for each country below.',
    'FCKUSTOM_GLOBAL_PASSWORD_TOOLTIP'                 => 'Enter your password matching the Merchant ID used. You have received this password in the welcome email from Kustom.',
    'FCKUSTOM_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'    => 'From the selection on the left, select the country for which you have received country-specific access data from Kustom.',
    'FCKUSTOM_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP' => 'Please enter the corresponding Merchant ID for this country here.',
    'FCKUSTOM_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'    => 'Please enter here the corresponding password for this country.',
    'FCKUSTOM_DEFAULT_COUNTRY_TOOLTIP'                 => 'Please choose from the list for which country the Kustom Checkout should be loaded by default, as long as the customer has not yet specified his country.',
    'FCKUSTOM_ENABLE_LOGGING_TOOLTIP'                  => 'Enables the logging function to record all API communication with Kustom into the mysql table fckustom_logs. This can be useful for analysis or troubleshooting. In productive mode, the function should be switched off, as otherwise table rows might increase quickly and sensitive data will be saved.',
    'FCKUSTOM_SEND_PRODUCT_URLS_TOOLTIP'               => 'Submit the URLs of the product detail pages of the products that are in your customer\'s shopping cart to Kustom so that Kustom can later link to your articles from the Kustom portal.',
    'FCKUSTOM_SEND_PRODUCT_IMAGES_TOOLTIP'             => 'Send the URLs of the product images of the products that are in your customers\' shopping cart to Kustom so that Kustom can display them in the Kustom portal.',
    'FCKUSTOM_ENABLE_ANONYMIZATION_TOOLTIP'            => 'Enable anonymization to hide the product names of products in your customers\' shopping cart from Kustom . This is e . g . recommended for online pharmacies, but should only be activated after consultation with Kustom .',
    'FCKUSTOM_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP' => 'If delivery to a different delivery address should be enabled, activate this button.',
    'FCKUSTOM_MANDATORY_PHONE_TOOLTIP'                 => 'If you want to require the specification of a telephone number, activate this switch. Normally for Kustom the telephone number is not mandatory.',
    'FCKUSTOM_MANDATORY_BIRTH_DATE_TOOLTIP'            => 'If you want to require the specification of a date of birth, activate this button. Usually for Kustom the date of birth is not mandatory. However, the information is necessary to allow the purchase on account or installment.',
    'FCKUSTOM_ENABLE_AUTOFOCUS_TOOLTIP'                => 'With this switch, you can set focus on the Kustom Iframe automatically when loading the page with the Kustom Checkout.',
    'FCKUSTOM_CHECKBOX_TOOLTIP'                        => 'There is a possibility that you can activate an additional checkbox within the Kustom Checkout Iframes to offer the customer, to open a customer account or to sign up for your newsletter, or both. If a checkbox was activated and user already has an account or signed up for the newsletter the text will be adjusted or hidden accordingly.',
    'FCKUSTOM_VALIDATION_TOOLTIP'                      => 'Hereby you can activate an additional check of the shopping cart, which validates the availability of the desired products again when sending the Kustom checkout order, in order to avoid errors through over sales. The mode \'Require successful validation\' is recommended.',
    'FCKUSTOM_SALUTATION_MANDATORY_TOOLTIP'            => 'This setting only applies to the Kustom checkout form for UK: Should input of a salutation be forced?',
    'FCKUSTOM_ENABLE_DHL_PACKSTATIONS_TOOLTIP'         => 'Currently not implemented',
    'FCKUSTOM_ENABLE_PRE_FILLING_TOOLTIP'              => 'Activate pre-filling of the Kustom Checkout Iframe with the data of the customer logged in to the OXID eShop',
    'FCKUSTOM_ENABLE_PREFILL_NOTIFICATION_TOOLTIP'     => 'If pre-filling of the Kustom Checkout Iframe is active, some countries require a corresponding privacy notice. This note is activated by this switch.',
    'FCKUSTOM_TERMS_AND_CONDITIONS_URL_TOOLTIP'        => 'Enter the URL to your terms and conditions here. This page will be linked from inside the Kustom Checkout Iframe. A valid URL starting with https:// must be specified.',
    'FCKUSTOM_CANCELLATION_RIGHTS_URL_TOOLTIP'         => 'Please specify the URL to your webpage containing the cancellation rights text. The URL must start with https:// .',
    'FCKUSTOM_SHIPPING_DETAILS_TOOLTIP'                => 'These shipping instructions will be shown to the customer on the thank you page after completing the order.',
    'FCKUSTOM_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'    => 'Assign this external payment method to one of the predefined payment methods',
    'FCKUSTOM_ENABLE_EXTERNAL_PAYMENT_TOOLTIP'         => 'With this switch, you activate this payment method as an external payment method for the Kustom Checkout. If active, the customer can select this payment method from the list of payment methods in the Kustom Checkout iframe.',
    'FCKUSTOM_ENABLE_EXTERNAL_CHECKOUT_TOOLTIP'        => 'With this switch, you activate this payment method as an external checkout. If active, this payment method will be displayed at the very bottom of the Kustom Checkout iframe before entering customer data.',
    'FCKUSTOM_EXTERNAL_PAYMENT_IMAGE_URL_TOOLTIP'      => 'Enter here the URL to an image which should be displayed next to the payment method in the Kustom Checkout Iframe. You ideally use a picture from a secure URL that starts with https: //.',
    'FCKUSTOM_EXTERNAL_CHECKOUT_IMAGE_URL_TOOLTIP'     => 'Enter here the URL to an image that should be displayed as a button for this payment method in the Kustom Checkout Iframe below. You ideally use a picture from a secure URL that starts with https: //.',
    'FCKUSTOM_EXTERNAL_IMAGE_URL_EMPTY'                => 'Please provide values for all languages.',
    'FCKUSTOM_EXTERNAL_IMAGE_URL_INVALID'              => 'Value must be a valid url starting with https://',
    'FCKUSTOM_EMD_CUSTOMER_INFO_TOOLTIP'               => 'This button activates the transmission of extra merchant data to Kustom, in this case the Customer Account Info, which includes the date of the customer account registration and its last modification.',
    'FCKUSTOM_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'        => 'This switch activates the transmission of extra merchant data to Kustom, in this case the Payment History Full, which contains the customer\'s previous purchases.',
    'FCKUSTOM_EMD_PAYMENT_TYPE_TOOLTIP'                => 'Please assign what kind of payment this payment method is.',
    'FCKUSTOM_EMD_HISTORY_FULL_TOOLTIP'                => 'Please specify here, if and which orders with this payment method should be included in the transfer of the order history of the customer. The dependency of the field OXORDER.OXPAID indicates whether only paid or all orders should be considered.',
    'FCKUSTOM_EMD_PASSTHROUGH_FIELD_TOOLTIP'           => 'It is possible with the help of a pass-through field to forward any other data to Kustom. To use this feature, you must install an appropriate module in the OXID eShop that writes the desired data into the pass-through field. A corresponding manual can be found in the developer documentation.',
    'FCKUSTOM_DISPLAY_ON_HOME_TOOLTIP'                 => 'With this switch, you activate a Kustom banner on your shop homepage in the standard themes Flow or Wave.',
    'FCKUSTOM_BANNER_SRC_TOOLTIP'                      => 'Here you can define the script tag for the banner integration. In the banner portal of Kustom you may find more banners to choose from.',
    'FCKUSTOM_FOOTER_PAYMENT_METHODS_TOOLTIP'          => 'With this switch, you activate the Kustom Payment Method Display in the footer of your shop in the standard themes Flow or Wave.',
    'FCKUSTOM_FOOTER_KUSTOM_LOGO_TOOLTIP'              => 'With this switch you insert the Kustom logo in the footer of your shop in the standard themes Flow or Wave.',
    'FCKUSTOM_BORDER_TOOLTIP'                          => 'Color of the frame, which appears in the shop frontend in the case of various available sub-options after selecting the Kustom payment method.',
    'FCKUSTOM_BORDER_SELECTED_TOOLTIP'                 => 'Color of the frame, which appears in the shop frontend in the case of various available sub-options after selecting the Kustom payment method. This color value is used to highlight the currently active sub-option.',
    'FCKUSTOM_BUTTON_TOOLTIP'                          => 'This setting has no effect at the time of publishing this module.',
    'FCKUSTOM_BUTTON_TEXT_TOOLTIP'                     => 'This setting has no effect at the time of publishing this module.',
    'FCKUSTOM_DESIGN_CHECKBOX_TOOLTIP'                 => 'Background color of the radio-buttons, which appear in the shop frontend in the case of various available sub-options after selecting the Kustom payment method',
    'FCKUSTOM_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'       => 'This setting has no effect at the time of publishing this module.',
    'FCKUSTOM_DETAILS_TOOLTIP'                         => 'Color of bullets in the presentation of payment details on the payment methods selection page.',
    'FCKUSTOM_HEADER_TOOLTIP'                          => 'This setting has no effect at the time of publishing this module.',
    'FCKUSTOM_LINK_TOOLTIP'                            => 'Color of the links within the detail description of the payment methods on the payment methods selection page.',
    'FCKUSTOM_TEXT_TOOLTIP'                            => 'Text color of the detailed description of the payment methods on the payment methods selection page.',
    'FCKUSTOM_SECONDARY_TEXT_TOOLTIP'                  => 'Alternative text color of the detailed description of the payment methods on the payment methods selection page.',
    'FCKUSTOM_BORDER_RADIUS_TOOLTIP'                   => 'With this setting, you can specify the degree of rounding of the frame, which appears in the shop frontend after selecting the Kustom payment method in case of different available sub-options.',

    'KUSTOM_ONLY_FOR_KUSTOM_PAYMENT'               => 'This tab is for Kustom orders only',
    'KUSTOM_CAPTURE_FULL_ORDER'                    => 'Full order capture',
    'KUSTOM_CAPTURE_ID'                            => 'Capture id',
    'KUSTOM_CAPTURE_REFERENCE'                     => 'Kustom reference',
    'KUSTOM_CAPTURE_AMOUNT'                        => 'Capture amount',
    'KUSTOM_CAPTURE_DATE'                          => 'Captured at',
    'KUSTOM_REFUND_AMOUNT'                         => 'Refund amount',
    'KUSTOM_REFUND_DESCRIPTION'                    => 'Refund description',
    'KUSTOM_REFUND_DATE'                           => 'Refunded at',
    'KUSTOM_CAPTURES'                              => 'Captures',
    'KUSTOM_REFUNDS'                               => 'Refunds',
    'KUSTOM_CANCEL_ORDER'                          => 'Cancel Order',
    'KUSTOM_ORDER_IS_CANCELLED'                    => 'Order is cancelled. ',
    'KUSTOM_SEE_ORDER_IN_PORTAL'                   => '<a href="%s" target="_blank" class="alert-link">See this order in the Kustom Portal.</a>',
    'KUSTOM_ORDER_NOT_IN_SYNC'                     => '<strong>Warning!</strong> This order\'s data is different on Kustom\'s side. ',
    'KUSTOM_MID_CHANGED_FOR_COUNTRY'               => '<strong>Wrong credentials!</strong> This order has been placed using <strong>%s</strong> merchant id. Currently configured merchant id for <strong>%s</strong> is <strong>%s</strong>.',
    'FCKUSTOM_KCO_INVOICE_MSG'                     => 'Your payment is processed by our partner Kustom. If you chose to pay directly, your payment is already complete. If you opted to pay later or over time you will shortly receive payment instructions from Kustom. You can manage all your payments via Kustom.com or in our app.',
    'FCKUSTOM_ORDER_UPDATE_CANT_BE_SENT_TO_KUSTOM' => 'Caution! Due to the current order status this order update can\'t be submitted to Kustom. Please manually adjust the order status in the Kustom Merchant Portal accordingly.',
    'FCKUSTOM_ORDER_UPDATE_REJECTED_BY_KUSTOM'     => 'Caution! Your last changes of the current order could not be processed by Kustom (Reason: %s). Please manually undo your recent changes in the OXID eShop or adjust the order in the Kustom Merchant Portal accordingly if necessary.',
    'KUSTOM_UNAUTHORIZED_REQUEST'                  => 'Unauthorized request. Check the general settings for Kustom to see if Merchant Id and Password are correct.',
    'KUSTOM_ORDER_NOT_FOUND'                       => 'This order could not be found in the ordering system of Kustom. That\'s why any changes to the order data will not be transmitted to Kustom.',
    'KUSTOM_GENERAL_ERROR'                         => 'An unknown error has occurred. The request could not be processed.',
    'FCKUSTOM_PRODUCT_NAME'                        => 'Product name',
    'FCKUSTOM_ANONYMIZED_PRODUCT'                  => 'Anonymized product title:',
    'FCKUSTOM_VOUCHER_DISCOUNT'                    => 'Coupon Discount',

    'FCKUSTOM_KCO_BUTTON_TOOLTIP'                    => 'Background color of the pay-button within the Kustom Checkout iframe.',
    'FCKUSTOM_KCO_BUTTON_TEXT_TOOLTIP'               => 'Color of the text of the pay-button inside the Kustom Checkout iframe.',
    'FCKUSTOM_KCO_DESIGN_CHECKBOX_TOOLTIP'           => 'Background color of the checkboxes within the Kustom Checkout iframe.',
    'FCKUSTOM_KCO_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP' => 'Color of the checkbox checkmark within checkboxes inside the Kustom Checkout iframe.',
    'FCKUSTOM_KCO_HEADER_TOOLTIP'                    => 'Color of headlines / titles within the Kustom Checkout iframe.',
    'FCKUSTOM_KCO_LINK_TOOLTIP'                      => 'Color of links within the Kustom Checkout iframe.',
    'FCKUSTOM_KCO_BORDER_RADIUS_TOOLTIP'             => 'With this setting, you can specify the degree of rounding of the Kustom Checkout Iframe.',

    'FCKUSTOM_GIFT_WRAPPING_TITLE' => 'Gift wrapping',
    'FCKUSTOM_GIFT_CARD_TITLE'     => 'Gift card',

    'FCKUSTOM_ERROR_SHOP_SSL_NOT_CONFIGURED' => 'Fatal error: It\'s mandatory to have a valid and SSL-secured (https) $this->sSSLShopURL configured in the config.inc.php of your shop to use the %s feature!',
    'FCKUSTOM_ERROR_WRONG_CREDS'             => '<strong>Wrong credentials!</strong>',
    'FCKUSTOM_ERROR_KCO_INACTIVE'            => 'Setup error: Kustom Checkout is inactive in the shop',

    'KUSTOM_CAPTURE_SUCCESSFULL'            => 'Order successfully captured in Kustom.',
    'FCKUSTOM_CAPUTRE_FAIL_ORDER_CANCELLED' => 'Order could not be captured, because it was already cancelled.',
    'FCKUSTOM_NO_REQUESTS_WILL_BE_SENT'     => 'Changes to this order will not be transmitted to Kustom.',
    'FCKUSTOM_ANONYMIZED_PRODUCT_TOOLTIP'   => 'Please enter the string which should be transmitted to Kustom instead of the real product title.',
    'FCKUSTOM_USER_GUIDE'                   => 'User Guide',
    'FCKUSTOM_REGISTER_NOW_BUTTON'          => 'Register now',
    'FCKUSTOM_LEARN_MORE_BUTTON'            => 'Learn more',

    'FCKUSTOM_CUSTOMER_TYPE'         => 'Allowed customer types',
    'FCKUSTOM_CUSTOMER_TYPE_TOOLTIP' => "Here you can define whether the shop should accept only B2C transactions (default setting), only B2B transactions or both B2C and B2B transactions. <br> Note: After changing the customer type, the browsers' session cache needs to be cleared in order to test the payment.",
    'FCKUSTOM_B2C'                   => 'B2C customers only',
    'FCKUSTOM_B2B'                   => 'B2B customers only',
    'FCKUSTOM_B2B_B2C'               => 'Mainly B2B and also B2C customers',
    'FCKUSTOM_B2C_B2B'               => 'Mainly B2C and also B2B customers',
    'FCKUSTOM_NEED_SUPPORT'          => 'Need support with the integration?',
    'FCKUSTOM_REACH_SUPPORT'         => 'Reach out to Kustom\'s Merchant support',

    'FCKUSTOM_EU_WARNING' => '<p>To comply with the EU Geoblocking Regulation it is highly recommended to enable all European countries and assign them to the Kustom Checkout payment method.</p><p>Missing countries: %s</p>',

    'FCKUSTOM_IS_ENABLED' => 'Enabled',
    'FCKUSTOM_IS_BUTTON_REPLACE' => 'Update Button Key',
    'FCKUSTOM_IS_REPLACE' => 'Get new Button Key',
    'FCKUSTOM_IS_BUTTON_REPLACE_TOOLTIP' => 'You may update the Button Key, if any configuration or identification data on Kustom side should require a change. Usually you can use a Button Key as long as you like once it\'s been generated.',
    'FCKUSTOM_IS_BUTTON_APEARANCE_HEADLINE' => 'Button Styling Settings',
    'FCKUSTOM_IS_VARIATION_TOOLTIP' => 'Please choose between a fully Kustom branded version of the button and a more neutral light variant.',
    'FCKUSTOM_IS_TAGLINE_TOOLTIP' => 'Please choose whether the color of the tagline text below the button should be light or dark.',
    'FCKUSTOM_IS_TYPE_TOOLTIP' => 'Please choose the desired label of the button.',
    'FCKUSTOM_IS_BUTTON_PREVIEW' => 'Preview of the button',
    'FCKUSTOM_IS_BUTTON_PLACEMENT_DETAILS' => 'Show on product details page',
    'FCKUSTOM_IS_BUTTON_PLACEMENT_BASKET' => 'Show on basket overview page',
    'FCKUSTOM_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS' => 'Allow separate shipping address',
    'FCKUSTOM_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP' => 'If delivery to a different delivery address should be enabled, activate this button.',
    'FCKUSTOM_IS_SETTING_DATE_OF_BIRTH_MANDATORY' => 'Date of birth mandatory',
    'FCKUSTOM_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP' => 'If you want to require the specification of a date of birth, activate this button. Usually for Kustom the date of birth is not mandatory. However, the information is necessary to allow the purchase on account or installment.',
    'FCKUSTOM_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY' => 'National ID number mandatory',
    'FCKUSTOM_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP' => 'Please choose whether you want to make the national identification number mandatory.',
    'FCKUSTOM_IS_BUTTON_SETTINGS_VARIATION' => 'Variation',
    'FCKUSTOM_IS_BUTTON_SETTINGS_TAGLINE' => 'Tagline',
    'FCKUSTOM_IS_BUTTON_SETTINGS_TYPE' => 'Type',
    'FCKUSTOM_IS_SETTING_PHONE_MANDATORY' => 'Phone number mandatory',
    'FCKUSTOM_IS_SETTING_PHONE_MANDATORY_TOOLTIP' => 'Please choose whether you want to make the phone number mandatory.',
    'FCKUSTOM_SHIPPING_KCO' => 'Shipping sets assignments for the Kustom Checkout',
    'FCKUSTOM_SHIPPING_KCO_DESC' => 'Please assign your defined shipping sets to the corresponding Kustom labels. By this assignment you can amongst others enable Packstation deliveries.',
    'FCKUSTOM_SHIPPING_SETTINGS' => 'Shipping sets',
    'FCKUSTOM_COMPLETE_REFUND' => 'Refund complete order',
    'FCKUSTOM_PACKSTATION_NO_SHIPPING_SET' => 'No active shipping sets found',

    'FCKUSTOM_AUTHPAYMENTMETHOD'                       => 'Used payment type: ',
    'FCKUSTOM_AUTHPAYMENTMETHOD_unknown'               => 'Kustom',
    'FCKUSTOM_AUTHPAYMENTMETHOD_pay_by_card'           => 'Credit Card',
    'FCKUSTOM_AUTHPAYMENTMETHOD_direct_debit'          => 'Direct Debit',
    'FCKUSTOM_AUTHPAYMENTMETHOD_direct_bank_transfer'  => 'Direct Bank Transfer',
    'FCKUSTOM_AUTHPAYMENTMETHOD_slice_it_by_card'      => 'Pay in 3',
    'FCKUSTOM_AUTHPAYMENTMETHOD_fixed_sum_credit'      => 'Financing',
    'FCKUSTOM_AUTHPAYMENTMETHOD_b2b_invoice'           => 'B2B invoice (Billie)',
    'FCKUSTOM_AUTHPAYMENTMETHOD_invoice'               => 'Invoice',
    'FCKUSTOM_AUTHPAYMENTMETHOD_pay_later_by_card'     => 'Pay later by Card',
);
